[project]
name = "reverse-string-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "numpy>=2.4.2",
    "pydantic>=2.12.5",
    "pyaml>=26.2.1",
    "tensorboard>=2.20.0",
    "pytorch-ignite>=0.5.0",
]

[project.scripts]
ignite-lmtt = "init_project:main"

[tool.setuptools.packages.find]
where = ["src"]
